### PR TITLE
Remove deprecation warnings on jQuery 3

### PR DESCRIPTION
**Pull request by stof**
The first commit makes our CI compatible with jQuery 3 (removing usage of the deprecated `.size()` method in tests).
The second commit removes usage of deprecated APIs of jQuery 3 (our code technically works on jQuery 3 without that, but triggers deprecation warnings when using jquery.migrate, which make it painful for our users trying to migrate away from deprecated APIs). Using `on()` instead of `bind` bumps the minimum version of jquery to 1.7. But this is OK IMO, as only jQuery 3 is still maintained nowadays, and jQuery 1.7 was released in 2014.

Closes https://github.com/harvesthq/chosen/issues/2729

### CODE REVIEW

**Comment by tjschuck** [comment]
@satchmorun @adunkman If one of you 👍's this, I'm fine merging it on @stof's behalf.

**Comment by tjschuck** [comment]
@stof This seems to have broken CI on master when merged: https://travis-ci.org/harvesthq/chosen/builds/267382751

**Comment by adunkman** [comment]
Easy fix: #2869.

**Comment by tjschuck** [comment]
Thanks @adunkman! :heart: :heart: :heart_eyes_cat: :heart:

**Pull request merged**
