### PR TITLE
Compress PNGs with zopflipng

### PR DESCRIPTION
**Pull request by atdt**
Zopfli is the most efficient DEFLATE compression algorithm, trading run-time
performance for file sizes that are typically 3-8% smaller than those produced
by zlib with the maximum compression setting. Its output is Deflate-compatible,
so no specialized decoder is needed.

This change was created by running zopflipng against all the PNG files in this
repository. The exact invocation was:

```
  git ls-files --exclude-per-directory=.gitignore -- '*.png' \|
    parallel zopflipng -m -y {} {} \;
```

### CODE REVIEW

**Comment by Krinkle** [comment]
:+1: 

<http://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/>

**Comment by koenpunt** [comment]
Thanks for your contribution, but ImageOptim includes zopfli, and I believe it is already in use. Besides that, @mlettini is doing a mayor overhaul on the css, and the sprite is updated as well, so while at it maybe he could apply the the image compression instead of having it at a separate change.

**Comment by mlettini** [comment]
https://github.com/harvesthq/chosen/commit/dcd6ea87fb34c61fabe1922a824b0dd7ee636392

:+1:

**Comment by Krinkle** [comment]
(which is pull #2479)

**Comment by pfiller** [comment]
Seems like it makes sense to close this and work on getting #2479 merged. Thanks anyways, @atdt.

**Pull request closed without merging**
