### PR TITLE
Fixing placeholder bug

### PR DESCRIPTION
**Pull request by ComeBurguburu**
When filling with placeholder the search don't work
https://github.com/harvesthq/chosen/issues/2184#issuecomment-68726482

### CODE REVIEW

**Comment by stof** [comment]
the Prototype implementation needs to be kept in sync

**Comment by ComeBurguburu** [comment]
Okay I check the proto version

**Comment by ComeBurguburu** [comment]
https://github.com/harvesthq/chosen/pull/2192

**Comment by tjschuck** [comment]
@ComeBurguburu Can you squash this into one commit?  [Instructions here](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request).

**Comment by ComeBurguburu** [comment]
Fatal : need a single revision

**Pull request closed without merging**
