### PR TITLE
remove duplicate background property

### PR DESCRIPTION
**Pull request by koenpunt**
@mlettini this should be fine right?

### CODE REVIEW

**Comment by pfiller** [comment]
@mlettini is on holiday at the moment so it'll be awhile before he weighs in.

I'm 👍 on this change. Chrome seems to be choosing the second rule (without the background color specified) so the line isn't even doing what we expect. I think this is an improvement.

Thanks, @koenpunt!

**Comment by mlettini** [comment]
+1

**Comment by koenpunt** [comment]
@mlettini valid point. Do we need the white background behind the image?

**Comment by mlettini** [comment]
I don't think so, and again, the rule without the white background is the one that browsers have been using.

**Comment by koenpunt** [comment]
Updated.

**Comment by mlettini** [comment]
+1!

**Pull request merged**
