### PR TITLE
Add docs for destroying Chosen

### PR DESCRIPTION
**Pull request by tjschuck**
As discussed on https://github.com/harvesthq/chosen/issues/2290 and https://github.com/harvesthq/chosen/issues/2424#issuecomment-144467347, this adds docs for destroying Chosen.

/cc @harvesthq/chosen-developers

### CODE REVIEW

**Comment by koenpunt** [comment]
Great start, but destroy isn't a event, it's a method ;)

**Comment by koenpunt** [comment]
The options page is probably more suited for documenting destroy?

**Comment by tjschuck** [comment]
> The options page is probably more suited for documenting destroy?

Two problems with that:

1. It's not an option (as you pointed out in your first comment!  It's a method).  Same reason initialization isn't documented on the options page either.

2. There's only _one_ options page, and the docs for destroy are different for the jQuery and Prototype versions :-\

**Comment by koenpunt** [comment]
Hm yeah, and `destroy` is the only method.. if we're strict we should create a separate section for "methods".

**Comment by koenpunt** [comment]
But 
> It's not an option (as you pointed out in your first comment! It's a method).

The events are also documented on this page.. So I guess we're not that strict anyway :sob:

**Comment by mav2287** [comment]
In my mind it would make the most sense to put this right under Custom Width Support on the main project page with all the other examples of usage. You could even do a simple demo with a button labeled destroy to illustrate it.

**Comment by tjschuck** [comment]
@koenpunt The header for that section was already a little odd, since one event was triggered and the other was triggerable.  I changed the header to hopefully better lump the three things into a more obvious section of "lifecycle" concerns.

It's not great, but barring a complete rewrite/restructing of the docs, I think it's okay...

Eh?

**Comment by koenpunt** [comment]
:+1:

**Pull request merged**
