### PR TITLE
Add option to enable case sensitive search

### LINKED ISSUE #2509: Option for case-sensitive search
Request: add a settings option to make case sensitive searches.

Use case: in my web app I have a drop down with a list of letters: a, b, c, ... A, B, C,... that get used a lot by the content editors. I'd like to speed up their workflow so instead of opening the drop down, pressing z then moving the arrow down (to move from z to Z), they can just press shit-z to get to Z directly.

### PR DESCRIPTION
**Pull request by koenpunt**
Fixes #2509 

Haven't tested this yet though..

### CODE REVIEW

**Comment by tjschuck** [comment]
@koenpunt Docs!

**Comment by pfiller** [comment]
Sure, this seems straightforward enough. I agree we should have docs :)

**Comment by koenpunt** [comment]
:sparkles:

**Comment by tjschuck** [comment]
:+1: :+1: :+1:

**Comment by pfiller** [comment]
Just tested this out and agree that it's good to go. Let's get it merged!

Thanks, @koenpunt!!

**Pull request merged**
