### PR TITLE
A11y updates

### PR DESCRIPTION
**Pull request by latagore**
### Summary

This builds on pull request #2596, addressing the last comments from @KITSKevinBonett and @cooperfellows (see https://github.com/harvesthq/chosen/issues/264#issuecomment-230268619, https://github.com/harvesthq/chosen/issues/264#issuecomment-232185234 and https://github.com/harvesthq/chosen/issues/264#issuecomment-232286392). It looks like this issue or code hasn't been updated for a couple months now, so hopefully these contributions help.

I added:
- `aria-hidden=false` to the dropdown when it is loaded. The aria-hidden attribute is toggled when the dropdown is opened and closed.
- the `hidden` attribute to the native `<select>` element, to indicate that it's hidden to all users.
- `aria-selected` attributes to selected results, to indicate to assistive technologies that some entries are selected.
- surrounded the highlighted result text with a `<strong>` element so there is an indicator which element is highlighted when CSS is disabled.

### References

Based on the pull request in #2596.  Addresses issue #264.

### CODE REVIEW

**Comment by latagore** [comment]
Discovered a bug where highlighting rows doesn't work correctly. I'm closing this and will re-open when I I fix it.

**Comment by latagore** [comment]
Will reopen this pull request when I'm more confident it's stable. Currently clicking on the results text in Chrome does not work because of the newly added `<strong>` element.

**Comment by latagore** [comment]
I removed the `<strong>` highlighting because, for some reason, Chrome will not fire `mouseup` or `click` events to the newly added `<strong>` element, which essentially breaks the widget. If anyone can provide any feedback, that would be great.

I also don't know the case for CSS-disabled browsing is very strong (pun not intended), since elements with the `hidden` attribute, `aria-hidden" attribute, CSS property `display: none` are displayed anyways, which can make for very confusing navigation. The highlighted row is indicated with the `aria-activedescendant` property, which I think is sufficient.

**Comment by trickydisco78** [comment]
Has this made it into a release yet?

**Comment by stof** [comment]
as it is not merged, no.

**Comment by latagore** [comment]
I don't think I should keep people's hopes up with this pull request. When I created this, I wasn't confident in the quality of the code I wrote. I still don't feel that I understand Chosen well enough to resolve the conflicts and integrate it well with the existing code.

**Pull request closed without merging**
