### PR TITLE
Added a placeholder text for single select search box

### PR DESCRIPTION
**Pull request by liorch88**
I added a placeholder option for the search box (defaults to empty) so users could add a text such as "search now"

### CODE REVIEW

**Comment by tjschuck** [comment]
Chosen already supports a default text placeholder -- see [the docs](http://harvesthq.github.io/chosen/#default-text-support).

**Comment by liorch88** [comment]
It supports a placeholder for the select, not for the search box.
For example, in the docs you linked to, when you click the select it opens up with a blank search field. My addition adds a place holder, so you could write something like "type wanted value or a sub string of it"

**Comment by tjschuck** [comment]
Aha.  Will reopen and mark as a feature request.  You'll have to await the @harvesthq/chosen-developers to determine whether it will be added.

**Comment by Jessekevon** [comment]
Any updates on this feature? Also looking for a good solution for this.

**Comment by pfiller** [comment]
In an effort to try and get Chosen's repository under control and to best serve the people who use the tool, we're closing pull requests that add new functionality. For the time being, we're only merging bug fixes and functionality changes that are inline with Chosen's current scope. This doesn't mean we won't ever consider this functionality, but it does mean that we're being realistic about the time constraints the project maintainers have to give to this project.

Sorry this has sat open so long @liorch88. The hope is that by getting things under control, we can get to a place in the future where we can once again start adding new functionality (at which point we'd come back to closed PRs like this). Thanks for your patience and understanding!

**Pull request closed without merging**
