### PR TITLE
Super fast chosen - lazy creation of chosen options 

### PR DESCRIPTION
**Pull request by codecracker2014**
This code of chosen can handle selects with options like 50,000 and more easily. I've tested it with 50,000 data it's working like anything.
This code has been written on 0.9.11 version of chosen, i'm still learning coffeescript so i need to put these changes in head rev. The idea is not to create all li elements in chosen instead create them on demand, with infinite scroll or search. 
If we add lazy creating of chosen elements then it can handle almost any amount of data, and we can also think about adding support for datasources like array or some remote datasource.
Creating this pull request just for discussion purpose, i need to implement this in coffeescript with latest chosen. 

### Summary

Provide a general description of the code changes in your pull request.

Please double-check that:

  - [ ] All changes were made in CoffeeScript files, **not** JavaScript files.
  - [ ] You used [Grunt](https://github.com/harvesthq/chosen/blob/master/contributing.md#grunt) to build the JavaScript files and tested them locally.
  - [ ] You've updated both the jQuery *and* Prototype versions.
  - [ ] You haven't manually updated the version number in `package.json`.
  - [ ] If necessary, you've updated [the documentation](https://github.com/harvesthq/chosen/blob/master/public/options.html).

See the [Pull Requests section of our Contributing Guidelines](https://github.com/harvesthq/chosen/blob/master/contributing.md#pull-requests) for more details.

### References

If your pull request is in reference to one or more open GitHub issues, please mention them here to keep the conversations linked together.

### CODE REVIEW

**Comment by koenpunt** [comment]
Thanks, but you’ve made the changes in the js file, and added that, so there’s no chance this getting merged. I’m going to close this for now. Please open a new PR when you have made the changes in the coffeescript files, and also make sure to have a look at the checklist in the PR template.

**Comment by codecracker2014** [comment]
@koenpunt agree with you, i've already mentioned same in my comment. I just wanted to highlight the idea of creating chosen elements lazily, this gives huge performance benefit. I've solved performance issue with this approach in a application which is on (v0.9.11 of chosen) and having drop downs with thousands of data. I want to implement this in latest version of chosen, so i just raised this for discussion purpose. I just wanted to know whether this change is ok before working on it.

**Comment by koenpunt** [comment]
> agree with you, i've already mentioned same in my comment.

I'm sorry, I actually stopped reading once I saw how the change was implemented. Also discussions are often better started as an issue instead of a PR.

And since the changes present in your committed file aren't obvious, because there's no way to view a diff of these changes, it's impossible to review/give feedback.

**Comment by codecracker2014** [comment]
@koenpunt  Below are changes in functionality:
1. dropdown elements (ul li ) will be created on the fly based on search parameter.
2. by default only first n(can be configurable) will be displayed.
3. If user selects any option then default elements will be nearby that option including that(for select).


Ok i'll share performance benefits shortly.

**Comment by codecracker2014** [comment]
@koenpunt please refer  below links for performance diff:
Data set size=16k
1. Existing chosen link- try to search 00e3 - http://plnkr.co/edit/XocBKHBgQkRiqNfySixN?p=preview
Result- browser goes to not responding mode.
2. Chosen with lazy approach - try to search 00e3   -http://plnkr.co/edit/XocBKHBgQkRiqNfySixN?p=preview
Result - you can perform any operation easily.

**Comment by koenpunt** [comment]
There's no point in comparing with a very outdated version of Chosen. If you take for example the latest version of Chosen, search works fine, it be a bit slow, but fine:

http://plnkr.co/edit/rlCJCtFyTDIMi44GT4En?p=preview

**Comment by koenpunt** [comment]
To emphasize; 0.9.11 was released on **3 Juli 2013**: https://github.com/harvesthq/chosen/releases/tag/v0.9.11

**Comment by codecracker2014** [comment]
Agree it's a bit slow but working.

**Pull request closed without merging**
