### PR TITLE
This ugliness will not stand

### PR DESCRIPTION
**Pull request by travismeyer**

### CODE REVIEW

**Comment by tjschuck** [comment]
Well okay ¯\\\_(ツ)_/¯

@travismeyer Just in case you're forking Chosen (which is totally cool with us :+1: ), you might also want to check out [Select2](https://select2.github.io), another popular fork, first.  Maybe they already did some of the things you're after.

**Comment by travismeyer** [comment]
Ha sorry, it was an internal joke that I mistakenly pushed here



On Fri, Jul 24, 2015 at 2:43 PM, T.J. Schuck <notifications@github.com>
wrote:

> Well okay ¯\_(ツ)_/¯
>
> @travismeyer <https://github.com/travismeyer> Just in case you're forking
> Chosen (which is totally cool with us [image: :+1:] ), you might also
> want to check out Select2 <https://select2.github.io>, another popular
> fork, first. Maybe they already did some of the things you're after.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harvesthq/chosen/pull/2376#issuecomment-124734903>.
>



-- 
/Travis

**Comment by travismeyer** [comment]
Love your guys' work tho — really stoked to be working with the source code

**Comment by tjschuck** [comment]
@travismeyer No worries — looking forward to any PRs you want to send our way! :heart: :heart: :heart_eyes_cat: :heart:

**Pull request closed without merging**
