### PR TITLE
Adds a semi-colon that was missing from the set up.

### PR DESCRIPTION
**Pull request by mlissner**
Super minor. Just a semi-colon.

### CODE REVIEW

**Comment by arunabhp75** [comment]
I don't get the ideas of triage, can someone help me out?

**Comment by koenpunt** [comment]
Thanks, but semicolons are optional in JavaScript

**Comment by koenpunt** [comment]
@arunabhp75 triage is about assisting or providing an outside look on issues, which could help in solving those. In this case this PR was probably overlooked, and you being directed here to triage brought it under the attention again. 👍🏼

**Comment by mlissner** [comment]
@koenpunt semi-colons are *sometimes* optional. The reason that I filed this fix is because when I copy/pasted the code from the documentation, my editor threw an error. Seems better to default to having it, so that copy/paste works properly?

I mean...do as you please, it's just a semi-colon, but it's the kind of thing that can trip up a JS newbie.

**Comment by koenpunt** [comment]
@mlissner the opposite is true; semicolons are _sometimes_ required. A nice writeup by @mislav here: http://mislav.net/2010/05/semicolons/

**Pull request closed without merging**
