### PR TITLE
Fixing placeholder bug

### PR DESCRIPTION
**Pull request by ComeBurguburu**
When someone fill the value of the placeholder the search stop working and show all result instead of "nothing found"

This pull request solved this issue

( I've closed my other pull request , this is the last one with only one commit /cc @tjschuck )

### CODE REVIEW

**Comment by ComeBurguburu** [comment]
Can someone merge it ?

**Comment by tjschuck** [comment]
@koenpunt You seemed most up-to-speed with https://github.com/harvesthq/chosen/issues/2184 if you want to review/+1/merge.

**Comment by koenpunt** [comment]
Checking it now, but I'm trying to figure out why the fix is so easy; just removing a line or two.

**Comment by koenpunt** [comment]
Also, this doesn't solve the problem in the prototype version.

**Comment by stof** [comment]
The change done in the Prototype version is indeed totally different

**Comment by ComeBurguburu** [comment]
/cc @koenpunt  : the question should be why this condition comparing placeholer and value didn't make sens or maybe old code to add placeholder with none-html5 browser

Sorry /cc @stof my bad I change the wrong line I update it

**Comment by koenpunt** [comment]
Please squash the commits. and it would be nice to have a little more descriptive commit message. Thanks!

**Comment by tjschuck** [comment]
[Squash instructions reminder](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request).

**Pull request closed without merging**
