### PR TITLE
Updated tests and grunt configuration

### PR DESCRIPTION
**Pull request by koenpunt**
- added the max_shown_results spec for prototype.
- replaced event.simulate library with something that can fire any event (namely `keyup`)
- updated the grunt tasks;
  - `watch` watch sources and tests, and build and run tests on change.
  - `watch:test` only watch for changes in test files.
  - `test` build all sources and runs all tests.
  - `test:jquery` build jquery source and run jquery tests.
  - `test:proto` build proto source and run proto tests.

### CODE REVIEW

**Comment by koenpunt** [comment]
✨  @harvesthq/chosen-developers @stof

**Comment by adunkman** [comment]
4a9f15fd633e8e1d061675b5ef8681bf70052d0c seems pretty unrelated and subjective (I tend to favor double quotes always since there’s no reason not to) and makes this diff pretty hard to review.  Can we pull that out into another PR if you’re heart-set on it?

**Comment by koenpunt** [comment]
> 4a9f15f seems pretty unrelated and subjective

True, but just trying to get some sort of consistency throughout the project. But I can move these changes to the #2738 branch,

**Comment by koenpunt** [comment]
> I tend to favor double quotes always since there’s no reason not to

I prefer single, because it doesn't require me to press shift to type it. 

But I removed that commit, do you have anything else to add to this? :)

**Pull request merged**
