### PR TITLE
Fixed placeholder bug

### PR DESCRIPTION
**Pull request by ComeBurguburu**
when we set the value of placeholder in field Chosen returns all results

### CODE REVIEW

**Comment by tjschuck** [comment]
@stof @koenpunt #2194 has popped back up over here now :grinning:

**Comment by koenpunt** [comment]
I'm good with this. @stof you still have any objections?

**Comment by stof** [comment]
I think this would also require using a real placeholder for the field instead of setting the default text in the value

**Comment by tjschuck** [comment]
@stof Is that a blocker for this PR, or just an additional enhancement to be made separately?

**Comment by koenpunt** [comment]
I'll run it through multiple browsers, until now I've only tested in Chrome Canary

**Comment by stof** [comment]
Well, I think the current implementation might use the placeholder text to run the search now in some cases

**Comment by sergioviniciuss** [comment]
@stof  I think it was implemented by getting the 'value' instead of the placeholder tag to keep the support to older browsers like IE8

**Comment by ComeBurguburu** [comment]
@sergioviniciuss is right !!!
the (fake)placeholder is set only when there are no selected item and the input is not focus, I guess that we can keep it as fake placeholder to keep compatibility.

@stof the value of the data-placeholder is only use once to change the color of the input (color: #999 like default HTML5 placeholder color) 
I didn't remove this condition.

but to run the search the placeholder is useless.
Placeholder is here to inform the user not the program.

**Comment by ComeBurguburu** [comment]
This bug remain in 1.4.0 @pfiller 
http://jsfiddle.net/97huf6tn/

**Comment by pfiller** [comment]
So, I'm _pretty_ sure that filtering out the default value is a relic of a time when we called `winnow_results` when Chosen was being set up. In other words, we were running the first "search" while the default value was sitting in the form field and we needed to match all elements. Was that stupid? Yes!  That's why we made that better at some point.

I don't think there's currently a way to have Chosen open and have the default text still living in the form field. If that's true, by the time `get_search_text` is called, we can assume the person using Chosen actually meant to type the value.

This is all a very long way of saying that I am :+1: on this change. Thanks, @ComeBurguburu!

**Comment by ComeBurguburu** [comment]
Thanks  @pfiller 

May we remove this branch create by @koenpunt  because is merged now https://github.com/harvesthq/chosen/tree/ComeBurguburu-master ?

**Comment by tjschuck** [comment]
@ComeBurguburu Branch deleted -- thanks!

**Pull request merged**
