### PR TITLE
A Bower Option

### PR DESCRIPTION
**Pull request by pfiller**
@tjschuck @stof @koenpunt 

I don't know about you, but I'm tired of people opening bower issues. I definitely do not want want to add generated js back into our repo, but I figured there had to be _some_ way to do this that would make most people happy.

I thought we could maybe point bower at the generated assets in our `gh-pages` branch, but was disappointed to learn that bower relies on git tags. It seems the only good option is to create a separate repo (as @zurb has done [with Foundation](https://github.com/zurb/bower-foundation)).

So, I've given it a shot. I've created a separate `bower-chosen` repo in my personal account. I didn't want to start it in Harvest's account in case we decide not to go this route. People might actually see it here, but there's little chance of that in my personal account.

This adds two new task:

- `grunt publish-bower`: writes a bower.json file and shoves it (along with the necessary jquery assets) out to the `bower-chosen` repo
- `grunt publish-release`: runs `gh-pages:gh-pages` as well as the `bower-release` task

That means our new deploy process would look like this:

1. Update version number in `package.json`
1. run `grunt prep_release` (builds our assets and generates a new zip)
1. Add generated .zip file to the Github release (and delete it from your local)
1. New version commit!
1. Publish the release (using the Github interface)
1. Run `grunt publish-release`

What do you think? Is this crazy? The only question I have is how this would work with other package managers (some people asked for NPM in #1433). Should we change the name of the other repo and call it `chosen-published`? 

Please share your thoughts!

Addresses #2261, #1845, #1556, #1908, #1641, #1333, #1698, etc. etc. etc.

### CODE REVIEW

**Comment by pfiller** [comment]
BTW, you can see what the generated output looks like here:
https://github.com/pfiller/bower-chosen

**Comment by koenpunt** [comment]
What is the reason that we can't push the release packages to the main repo? Because like I see it, the contents of the release package in your bower repo is fine to use as a release package on the main repo.. Or was it that bower depends on the automatically generated tag-package..? Can't remember..

**Comment by adunkman** [comment]
Have you looked into https://github.com/bower/registry/pull/78? I haven’t, but having another repo seems really… gross. I agree it’s less gross than build files in a source repo, but I think this is very clearly a problem with Bower, and seems like something we wouldn’t want to address in Chosen. 

I believe that issue suggests that you can publish versions with something a-like:

```sh
bower register chosen http://harvesthq.github.io/chosen/1.4.0/
```

… but I’m not 100% sure.

**Comment by adunkman** [comment]
Oh, nevermind — seems like that issue supports loading git repositories over http and https, but they’re still required to be git repositories (as per discussion on https://github.com/bower/registry/issues/23).

**Comment by stof** [comment]
@koenpunt the issue with having the compiled files in the main repo is that it leaves us with 2 options:

- updating the dist file in the repo only for releases. Drawback is that all other commits are in an inconsistent state, which is bad (and breaks things for people expecting to get a dev version with bower)
- updating the dist file all the time. this is what we did previously, and it means that all PRs will conflict all the time, making the maintenance a huge nightmare.

@pfiller npm should not be an issue, given that it does not get the code from github (you publish the dist code to the npm registry AFAIK). So npm would not need this special repo.
Note that you should add the Chosen team as collaborators on your repo too, so that other people than you can create releases as well. Having it in the same organization would make it easier by reusing the same Github team instead of duplicating the collaborator management

**Comment by stof** [comment]
@pfiller I think the bower-chosen repo should contain a small Readme file explaining the goal of this repo and pointing to the chosen repo for contributions (and issues should be disabled on the repo)

**Comment by koenpunt** [comment]
@stof I don't mean including them in the repo, just in the published archive ;)

**Comment by pfiller** [comment]
I agree that it's gross to have a separate repo for the generated files, but the dependency on tags doesn't leave us a lot of wiggle room if we decide to support bower. The really nice thing about this is that, once it's set up, this flow doesn't require any extra work on our part. It doesn't seem like the extra repo will need much, if any, maintenance.

> I think the bower-chosen repo should contain a small Readme file explaining the goal of this repo and pointing to the chosen repo for contributions (and issues should be disabled on the repo)

100% yes. A link back to the main Chosen repo should exist anywhere it's possible.

> Note that you should add the Chosen team as collaborators on your repo too, so that other people than you can create releases as well. Having it in the same organization would make it easier by reusing the same Github team instead of duplicating the collaborator management.

Yes! Hadn't thought of that. One thing to note is that you'd need to add a "Personal access token" to your GitHub account for authenticating to the repo via the command line the way it's set up right now. Although, I suppose that might not be necessary if it's in the same organization.

Anywho, it seems like nobody has any blocking feedback on the actual implementation of this. It's really just a question of if you think we should do it or not. Bower generates a lot of noise and I'd like to try and do things to make this repo less noisy. That way, when we're spending time on Chosen, it's on things that actually matter.

A :+1: or :-1: from you guys would be real helpful. If it's +1'ed in concept, I'll go ahead and change the repo to harvest and add y'all.

**Comment by stof** [comment]
@koenpunt the issue is precisely that Bower does not support using the published archives

**Comment by stof** [comment]
:+1: on this concept

Btw, foundation is updating it from Travis-CI for each push to the main repo, so that even dev versions are available. What do you think about this idea (it would also solve the collaborator thing as only Travis would need the access) ?

**Comment by koenpunt** [comment]
:+1: for automated builds on commit, and maybe a travis setup could be a nice reboot of our testing attempts :)

**Comment by Ninir** [comment]
:+1: Yeah, interesting idea. How much work do you guys think you would need to fix this?

**Comment by pfiller** [comment]
Going to merge this and get it working with Travis today!

**Comment by pfiller** [comment]
Published: `bower install chosen`

**Comment by Ninir** [comment]
:+1: Great work guys!

**Pull request merged**
