### PR TITLE
Add ability to set images for select options

### PR DESCRIPTION
**Pull request by banesto**
If following markup:
```
<select data-placeholder="Choose a country..." class="chosen-select-images" style="width:350px;" tabindex="19">
  <option data-img-src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/0.7.1/flags/4x3/be.svg">Belgium</option>
  <option data-img-src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/0.7.1/flags/4x3/lv.svg" selected>Latvia</option>
  <option data-img-src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/0.7.1/flags/4x3/us.svg">USA</option>
  <option data-img-src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/0.7.1/flags/4x3/jp.svg">Japan</option>
  <option>Neverland</option>
</select>
```
and setup is in place:
```
$(".chosen-select").chosen({option_images: true});
```

it's possible to display images next to options in results dropdown and selected choices:
chosen-options-image

### CODE REVIEW

**Comment by tjschuck** [comment]
See also: https://github.com/harvesthq/chosen/pull/692

**Comment by banesto** [comment]
Should it mean that it will not be merged for at least 3 forthcoming years or what? :smile:

**Comment by tjschuck** [comment]
Not necessarily, but the biggest blocker to something like this getting merged is certainly much more philosophical than just the code.

Chosen is intended to be a drop-in replacement for a native `select`, with an eye towards progressive enhancement.  Native `select`s have no such templating functionality, so this is (perhaps) a step too far outside the goals of the project.

That's not to say it would _never_ be added, but features that break the bounds of native `select`s functionality are always a difficult consideration.

For a different philosophical take, you can consider [Select2](https://select2.github.io), which was originally a fork of Chosen.  Select2 _does_ offer templating, as well as countless other features that have been considered for Chosen but ultimately decided against.  Select2 seeks to be much more configurable, but potentially at the cost of complexity.

**Comment by banesto** [comment]
Ok, that's what I thought. Thank you for explanation.

**Comment by banesto** [comment]
I was thinking also about setting results via ajax and that's clearly out of chosen scope. As for image display in options, I consider it to be a tiny visual tweek for original html's select and that could possibly be in the scope.

**Comment by tjschuck** [comment]
@banesto Heh, may I point you to https://github.com/harvesthq/chosen/pull/166?

**Comment by pfiller** [comment]
In an effort to try and get Chosen's repository under control and to best serve the people who use the tool, we're closing pull requests that add new functionality. For the time being, we're only merging bug fixes and functionality changes that are inline with Chosen's current scope. This doesn't mean we won't ever consider this functionality, but it does mean that we're being realistic about the time constraints the project maintainers have to give to this project.

Sorry this has sat open so long @banesto. The hope is that by getting things under control, we can get to a place in the future where we can once again start adding new functionality (at which point we'd come back to closed PRs like this). Thanks for your patience and understanding!

**Pull request closed without merging**
