### PR TITLE
Add functionality to allow templates

### PR DESCRIPTION
**Pull request by cjstewart88**
I've added the functionality to allow templates in dropdowns by using the `data` attribute on `options` and a `template` option when setting up chosen.

I've compiled the code and provided jquery and prototype examples.

Below is the jQuery example.

### DOM:

    <select data-placeholder="Choose your favorite candy..." class="chzn-select-template-example" style="width:350px;" tabindex="11">
      <option value=""></option>
      <option data-type="chocolate" data-user-rating="1.8">M&Ms</option>
      <option data-type="fruity" data-user-rating="1">Starburst</option>
      <option data-type="fruity" data-user-rating="7">Skittles</option>
      <option data-type="chocolate" data-user-rating="9">Reese's</option>
      <option data-type="chocolate" data-user-rating="10">Snickers</option>
    </select>

### Initialize It:

    $(".chzn-select-template-example").chosen({
      template: function (text, templateData) {
        return [
          "<span style='float: right'>User Rating: " + templateData.userRating + "</span>",
          "<div>" + text + "</div>",
          "<div><i>type of candy: " + templateData.type + "</i></div>"         
        ].join("");
      }
    });

### Result:

image

Thanks to Elliott Wood for code reviewing and to Select2 for inspiration.

### CODE REVIEW

**Comment by sshishov** [comment]
It seems that due to this delay all possible users of the plugin will migrate to select2 in spite of it is heavy but it more configurable.

**Comment by adrien-be** [comment]
Chosen vs Select2: make up your mind ;) http://stackoverflow.com/a/28153011

**Comment by trungdq88** [comment]
Hi, 
Is this pull request merged yet? Because I could not get this work on Chosen v1.4.1 (latest for now).

**Comment by cjstewart88** [comment]
No it's not, sorry man. Check out select2 if you need templating.

**Comment by pfiller** [comment]
In an effort to try and get Chosen's repository under control and to best serve the people who use the tool, we're closing pull requests that add new functionality. For the time being, we're only merging bug fixes and functionality changes that are inline with Chosen's current scope. This doesn't mean we won't ever consider this functionality, but it does mean that we're being realistic about the time constraints the project maintainers have to give to this project.

Sorry this has sat open so long @cjstewart88. The hope is that by getting things under control, we can get to a place in the future where we can once again start adding new functionality (at which point we'd come back to closed PRs like this). Thanks for your patience and understanding!

**Comment by sshishov** [comment]
4 years back it was opened and now closed due to lack of time?! LOL sounds rediculous

**Comment by razvaniacob** [comment]
This would be awesome! Why wasn't merged?

**Comment by rafwell** [comment]
+1 from brazilian developers! thanx!

**Comment by groovenectar** [comment]
Here is another way to do it for now...

You can add special characters that will still look okay in a normal select, but not normally appear in the text. For example `TITLE :: Description`. Then find the  `::`  and format using that. This example is designed for single select. For multiple you would probably just have to change the `.chosen-single`, or use another way to select it.

	$('select[name="SELECT_NAME"]')
		.chosen({search_contains: true})
		.add('.chosen-search')
		.on('chosen:showing_dropdown keyup change', function() {
		$('.chosen-results .active-result, .chosen-single span').html(function() {
			var html = $(this).html();
			if (/ :: /.test(html)) {
				return '<strong>' + html.replace(' :: ', '</strong> <span style="font-size:70%;display:inline;font-weight: normal;">') + '</span>';
			} else {
				return html;
			}
		});
	});

Your result in this example should be `<strong>Title</strong> <span style="font-size:70%;display:inline;font-weight: normal;">Description</span>`

**Comment by TylerRick** [comment]
Select2 for the win (https://select2.org/dropdown). Coming from Select2 to Chosen in the project I'm working on, I was sad to see this feature missing...

**Pull request closed without merging**
